### ISSUE TITLE
How to make debian in termux case-sensitive?

### ISSUE THREAD

**Issue by yuyueshihaoren** [MFDGaming/debian-in-termux#1]

**Comment by yuyueshihaoren** [comment]
> In debian in termux, it is case-insensitive
> When I try to touch H and then touch h, it says cannot touch 'h': File exists
> How to make the virtual filesystem case-insensitive? Otherwise, pam.7.gz cannot coexist with PAM.7.gz

I later found out that on my tablet it is case-insensitive but on my phone it is case-sensitive.
What funny is: other places in termux are case-sensitive and ~/storage/shared is case-insensitive on both of my devices.
It is really confusing.
(I mainly want to use debian on my tablet. My phone is just too small)

**Comment by MFDGaming** [comment]
What do you mean
